package jinyuanyuan.bw.com.jinyuanyuan0120.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jinyuanyuan.bw.com.jinyuanyuan0120.bean.GoodsDataBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDataBeanDaoConfig;

    private final GoodsDataBeanDao goodsDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDataBeanDaoConfig = daoConfigMap.get(GoodsDataBeanDao.class).clone();
        goodsDataBeanDaoConfig.initIdentityScope(type);

        goodsDataBeanDao = new GoodsDataBeanDao(goodsDataBeanDaoConfig, this);

        registerDao(GoodsDataBean.class, goodsDataBeanDao);
    }
    
    public void clear() {
        goodsDataBeanDaoConfig.clearIdentityScope();
    }

    public GoodsDataBeanDao getGoodsDataBeanDao() {
        return goodsDataBeanDao;
    }

}
